// Mock data for 醒书日记 prototype
window.TAGS = [
  '积极主动', '以终为始', '要事第一', '双赢思维',
  '移情聆听', '统合综效', '知止有定', '修身为本',
  '格物致知', '君子慎独', '诚中形外', '十目所视',
  '有斐君子', '克明峻德', '日新又新', '听讼无讼',
  '正心修身', '絜矩之道', '生财有道', '以义为利',
];

// Avatar hues for placeholder avatars (oklch hue)
const HUES = [30, 60, 200, 240, 280, 350, 15, 100];

window.SEED_DIARIES = [
  {
    id: 1,
    title: '晨起读《大学》三十分钟',
    author: '砚秋',
    avatarHue: 35,
    content:
      '今日五点半起床，泡一壶老白茶，翻开《大学》。\n\n"知止而后有定，定而后能静，静而后能安，安而后能虑，虑而后能得"。每读一次，体会更深一层。今日所悟：知止，并非止步不前，而是知所止——明确边界与方向。心若无止，则终日逐物，劳而无功。\n\n记下三件今日要事：写完季度复盘、与父母通话、整理书柜。先做要紧不紧急之事。',
    time: '今天 06:42',
    timestamp: '2026-05-14 06:42',
    tags: ['修身为本', '知止有定', '要事第一'],
    permission: 'public',
    likes: 48,
    favorites: 12,
    comments: 6,
    shares: 2,
    isLiked: false,
    isFavorited: true,
    authorIsMember: true,
  },
  {
    id: 2,
    title: '与同事一次艰难的谈话',
    author: '陆明远',
    avatarHue: 200,
    content:
      '今天和团队成员谈绩效问题。本想直接指出问题，但提醒自己——先理解，再被理解。\n\n听他讲了二十分钟，了解到家中情况的变化。后面的对话变得顺畅许多。最终我们一起制定了下一阶段的目标。\n\n移情聆听不是技巧，是修养。',
    time: '昨天 22:18',
    timestamp: '2026-05-13 22:18',
    tags: ['移情聆听', '双赢思维'],
    permission: 'member',
    likes: 124,
    favorites: 38,
    comments: 21,
    shares: 9,
    isLiked: true,
    isFavorited: false,
    authorIsMember: true,
  },
  {
    id: 3,
    title: '关于"慎独"的一点思考',
    author: '叶清和',
    avatarHue: 280,
    content:
      '《中庸》言："君子慎其独也"。独处时所为，最见心性。今日独自在家，本想刷一晚短视频，转念把手机放进抽屉，读完了搁置许久的《明史纪事本末》第三卷。\n\n慎独不在大事，而在不被看见的小事里。',
    time: '5月12日',
    timestamp: '2026-05-12 23:05',
    tags: ['君子慎独', '修身为本'],
    permission: 'member',
    likes: 86,
    favorites: 24,
    comments: 11,
    shares: 4,
    isLiked: false,
    isFavorited: false,
    authorIsMember: true,
  },
  {
    id: 4,
    title: '今日的复盘与明日的清单',
    author: '林知微',
    avatarHue: 15,
    content:
      '日新又新——这是今天反复想到的四个字。每一天若不是新的，便是浪费的。\n\n复盘今日：上午写作两小时（达标）、下午会议偏多（待优化）、晚间陪孩子读书四十分钟（满意）。\n\n明日要事：① 完成提案初稿 ② 跑步五公里 ③ 给久未联系的老友打电话。',
    time: '5月11日',
    timestamp: '2026-05-11 21:30',
    tags: ['日新又新', '要事第一'],
    permission: 'public',
    likes: 32,
    favorites: 9,
    comments: 3,
    shares: 1,
    isLiked: false,
    isFavorited: false,
    authorIsMember: false,
  },
  {
    id: 5,
    title: '私密 · 关于父亲的一段记忆',
    author: '我',
    avatarHue: 60,
    content: '只写给自己看。\n\n父亲今天来电话，说院里的桂花树开了。',
    time: '5月10日',
    timestamp: '2026-05-10 19:00',
    tags: ['诚中形外'],
    permission: 'private',
    likes: 0,
    favorites: 0,
    comments: 0,
    shares: 0,
    isLiked: false,
    isFavorited: false,
    authorIsMember: false,
    isMine: true,
  },
  {
    id: 6,
    title: '生财有道，先义而后利',
    author: '苏景行',
    avatarHue: 100,
    content:
      '《大学》后篇专论"生财之大道"。生之者众，食之者寡，为之者疾，用之者舒，则财恒足矣。\n\n创业八年，越来越觉得：长久的利，必先源于义。短期的取巧，往往是长期的损失。',
    time: '5月9日',
    timestamp: '2026-05-09 15:40',
    tags: ['生财有道', '以义为利'],
    permission: 'public',
    likes: 215,
    favorites: 67,
    comments: 38,
    shares: 22,
    isLiked: false,
    isFavorited: true,
    authorIsMember: true,
  },
  {
    id: 7,
    title: '统合综效 · 一次跨部门协作',
    author: '何怀瑾',
    avatarHue: 240,
    content:
      '今天主持的项目协调会，财务、技术、市场三方意见相左。会前我做了一件事：把每个部门的核心诉求各自梳理一遍，会上请他们先听对方，再讲自己。\n\n一加一不是二，是三、是更多——这便是统合综效。',
    time: '5月8日',
    timestamp: '2026-05-08 18:12',
    tags: ['统合综效', '双赢思维'],
    permission: 'public',
    likes: 67,
    favorites: 18,
    comments: 7,
    shares: 3,
    isLiked: true,
    isFavorited: false,
    authorIsMember: false,
  },
  {
    id: 8,
    title: '格物致知 · 一杯茶的滋味',
    author: '砚秋',
    avatarHue: 35,
    content:
      '友人寄来一饼老白茶，我连泡了七道，每一道留心其香、其色、其韵。\n\n格物，是细察万物之理；致知，是由物及心。一杯茶里有四季，也有节制与丰饶之道。',
    time: '5月7日',
    timestamp: '2026-05-07 10:25',
    tags: ['格物致知'],
    permission: 'public',
    likes: 54,
    favorites: 16,
    comments: 4,
    shares: 1,
    isLiked: false,
    isFavorited: false,
    authorIsMember: true,
  },
];

window.SEED_COMMENTS = [
  {
    id: 'c1',
    diaryId: 1,
    user: '陆明远',
    avatarHue: 200,
    content: '"虑而后能得"——今天读到这里也停了很久。',
    time: '2小时前',
    replies: [
      { id: 'c1-1', user: '砚秋', avatarHue: 35, content: '同道。共勉。', time: '1小时前' },
    ],
  },
  {
    id: 'c2',
    diaryId: 1,
    user: '叶清和',
    avatarHue: 280,
    content: '请问砚秋老师，老白茶是哪个山头的？',
    time: '30分钟前',
    replies: [],
  },
  {
    id: 'c3',
    diaryId: 1,
    user: '我',
    avatarHue: 60,
    content: '收藏了。今日要事第一要紧——明日开始尝试。',
    time: '刚刚',
    replies: [],
    isMine: true,
  },
];

window.CURRENT_USER = {
  // 默认采用微信授权名称
  wechatName: '清逸',
  // 可编辑字段
  nickname: '清逸',       // 默认 = wechatName
  realName: '',           // 真实姓名，留空表示未填
  phone: '138****6082',
  avatarHue: 60,
  // 'guest' 未授权 · 'authed' 已授权用户 · 'member' 会员
  identity: 'authed',
  // 会员信息（identity === 'member' 时使用）
  memberFrom: '2026-02-24',
  memberUntil: '2027-02-24',
  daysLeft: 286,
  // 管理员后台创建的最新订单
  latestOrder: {
    id: 'XS-20260224-0871',
    amount: 365,
    method: '线下转账',
    createdBy: '管理员 · 砚秋',
    createdAt: '2026-02-24 10:32',
    status: 'paid',          // pending / paid
  },
  stats: {
    diaries: 14,
    likes: 326,
    favorites: 89,
    comments: 47,
    shares: 12,
  },
};

window.ADMIN_CONTACT = {
  name: '运营 · 砚秋',
  wechat: 'xingshu-ops',
  hours: '工作日 09:00 – 18:00',
  note: '请备注您的微信昵称与手机号，便于核对身份。',
};


// ── 醒书活动 mock（v2.1 活动模块原型）──
window.SEED_ACTIVITIES = [
  {
    id: 101,
    title: '五月共读会：把《大学》读进日常',
    coverHue: 60, coverChar: '讀',
    datetime: '5月24日（周六）14:00 – 16:30',
    type: 'offline', city: '广州',
    location: '天河 · 方所书店 活动区',
    organizer: '醒书运营组',
    capacity: 30, signedUp: 21, signedByMe: false,
    deadline: '5月23日 12:00 报名截止',
    status: 'upcoming',
    notice: '请提前 10 分钟到场；建议携带纸质笔记本。',
    content:
      '一起精读《大学》"修身为本"章，围绕"知止而后有定"展开两小时的深度讨论。\n\n流程：领读人导读（30 分钟）→ 分组讨论（60 分钟）→ 每人一句"今日所悟"（30 分钟）。\n\n没有门槛，只需要你带着最近一周的一个真实困惑而来。',
  },
  {
    id: 102,
    title: '线上夜谈：写日记的第一百天',
    coverHue: 240, coverChar: '談',
    datetime: '5月28日（周三）20:30 – 21:30',
    type: 'online', city: '',
    location: '腾讯会议（报名后获取入会链接）',
    organizer: '醒书运营组',
    capacity: 100, signedUp: 63, signedByMe: true,
    deadline: '5月28日 18:00 报名截止',
    status: 'upcoming',
    notice: '线上活动，请提前测试麦克风；全程可只听不发言。',
    content:
      '三位坚持记录超过一百天的醒书人，分享他们的方法与"写不下去的时刻"。\n\n你会听到：如何用五分钟写完一篇不敷衍的日记；停更两周之后怎么回来；以及记录如何悄悄改变了他们对家人的耐心。',
  },
  {
    id: 103,
    title: '城市走读：越秀山晨行与静坐',
    coverHue: 120, coverChar: '行',
    datetime: '6月1日（周日）07:00 – 09:30',
    type: 'offline', city: '广州',
    location: '越秀公园 正门集合',
    organizer: '醒书 · 同城小组',
    capacity: 15, signedUp: 15, signedByMe: false,
    deadline: '5月31日 20:00 报名截止',
    status: 'upcoming',
    notice: '穿舒适的鞋；活动免费，早餐自理。',
    content:
      '一次不带手机的晨行。七点集合，沿越秀山步道慢行四十分钟，山顶静坐十五分钟，之后围坐分享——只聊一个问题："最近，你为谁做过一件小事？"',
  },
  {
    id: 104,
    title: '四月回顾：一起读《高效能人士的七个习惯》',
    coverHue: 30, coverChar: '習',
    datetime: '4月19日（周六）14:00',
    type: 'offline', city: '广州',
    location: '天河 · 方所书店',
    organizer: '醒书运营组',
    capacity: 30, signedUp: 28, signedByMe: false,
    deadline: '',
    status: 'past',
    content: '',
    review: {
      text: '二十八位醒书人到场。我们用"要事第一"做了各自下周的计划，散场时有人说：这是第一次在书店里聊到不想走。\n\n三个瞬间值得记住：一位妈妈说她把"双赢思维"用在了和女儿的争执里；两位第一次见面的书友约好下周互相监督晨读；最后的合影里，每个人手里都举着自己写下的一句话。',
      photos: 4,
    },
  },
  {
    id: 105,
    title: '三月回顾：线上分享「日记与自我对话」',
    coverHue: 320, coverChar: '省',
    datetime: '3月26日（周三）20:30',
    type: 'online', city: '',
    location: '腾讯会议',
    organizer: '醒书运营组',
    capacity: 100, signedUp: 87, signedByMe: false,
    deadline: '',
    status: 'past',
    content: '',
    review: {
      text: '八十七人在线。主讲人分享了"给三年后的自己写信"的练习，当晚就有十一位醒书人发布了自己的第一封信。',
      photos: 2,
    },
  },
];
